### PR TITLE
fix(caption-parser): do not fail when first sei sample is null

### PR DESCRIPTION
**Pull request by sgrogov**
By following up on <a href="https://github.com/videojs/mux.js/issues/223">that discussion</a>, maybe this small fix will be enough?

### CODE REVIEW

**Comment by nicklive** [comment]
Hi, guys! Any plans for merging this pr?

**Comment by gkatsev** [comment]
@nicklive hey, do you have any test content you can share with us to test this?

**Comment by carloscarnero** [comment]
I've observed [the same bug](https://github.com/videojs/mux.js/issues/223) in a couple of streams I have (at some point the player stops and the loading spinner begins). Manually modifying the source code as in this PR fixes this particular problem.

@gkatsev What would be a good method of sharing content? Currently, I can't publish it over HTTP but I could make it available to you by other means.

**Comment by gkatsev** [comment]
If you can attach the file here to github that works, if you need to give it to me privately, feel free to either send it to me on [our slack](http://slack.videojs.com) or via email.

**Comment by carloscarnero** [comment]
> If you can attach the file here to github that works, if you need to give it to me privately, feel free to either send it to me on [our slack](http://slack.videojs.com) or via email.

@gkatsev [Attached](https://github.com/videojs/mux.js/files/3023323/screensaver.zip) you can find a (hopefully) reduced test case scenario. Peeking on the console, it can be seen that the error manifests around 18 seconds, and playback stops at 1:06 (the 11th segment).

When using other players, the playback completes successfully.

**Comment by gkatsev** [comment]
Thanks! I can see it failing and working with this fix. I wonder if we still want to push the seiNal unit into the results, even without the pts/dts values. @squarebracket thoughts?

Also, not sure what's up with travis.

**Comment by squarebracket** [comment]
I can't see any reason that _not_ pushing an empty NAL would cause a problem, since the caption parser will disregard any non-caption packets before it does any processing on them. Might want to get @ldayananda to chime in here, though, since she wrote this particular bit of code.

**Comment by ldayananda** [comment]
I think this change is hiding another potential issue. It looks like a matching sample is not found because the start of the SEI NAL in seg11 in the provided example starts at a point(`189975`) outside the samples in the stream(samples end at `189971`) so this call returns null

https://github.com/videojs/mux.js/blob/009f769128c82932949c99508dea5d2d0a9f4bd2/lib/mp4/caption-parser.js#L78

**Comment by carloscarnero** [comment]
@ldayananda Does that means that there's an actual possibility that the transcoding/packaging process that generated those artifacts is defective? This is worrying for me since that process is completely controlled by me via custom ffmpeg pipelines; so that means that I'd need to revise them.

OTOH, neither hls.js nor other players (Bitmovin, JWPlayer, et al.)

**Comment by gkatsev** [comment]
Closing in favor of #321.

**Pull request closed without merging**
