### PR TITLE
fix: emit pts values instead of dts

### PR DESCRIPTION
**Pull request by brandonocasey**
See https://github.com/videojs/http-streaming/pull/624

It seems that most browsers use pts these days, and we get better results with it.

### CODE REVIEW

**Comment by gkatsev** [comment]
@joeyparrish we've recently started getting more and more issues around video underflow, which stems around our usage of DTS here. From what we can tell, we used to use DTS here due to some bug in an old version of Firefox that used DTS timing rather than PTS timing but given that all browsers have moved to PTS we should do the same.
However, we want to make sure that Shaka doesn't break if we make this change and are considering whether this should be a patch/minor or maybe a major version update to mux.js.
Any input on this change and whether and how it'll affect Shaka would be appreciated.

**Comment by joeyparrish** [comment]
@gkatsev, I think PTS is correct, and you should make the change.  I'll leave it to your discretion what the version number change should be.  We'll test the new version as soon as you can point me at a minified build that always does PTS, and if we need to adjust something in Shaka Player to match, we will.  If it's a trivial upgrade, we'll make it in the current v2.5.x branch, and if not, we'll make it in the next minor release, v2.6.0.

**Comment by gkatsev** [comment]
Thanks @joeyparrish. We have a couple of other related changes that are in the pipeline, so, we may just do it all at the same time and do a major version update to just to be on the safe side.

**Comment by joeyparrish** [comment]
Okay, sounds good.

**Comment by gkatsev** [comment]
Let's make it a minor and if anyone complains, we can revert and make it a major

**Pull request merged**
