### PR TITLE
change code example transmuxer event listeners

### PR DESCRIPTION
**Pull request by arturparkhisenko**
Resolves https://github.com/videojs/mux.js/issues/407 and https://github.com/videojs/mux.js/issues/323
Context is in [407](https://github.com/videojs/mux.js/issues/407).

A mini contribution for https://hacktoberfest.com/ if you'll be kind to add the label `hacktoberfest-accepted` for this PR. Thanks!

### CODE REVIEW

**Comment by arturparkhisenko** [comment]
@alex-barstow thought to ask for your review if you'll have a moment. Thanks

**Comment by arturparkhisenko** [comment]
cc @wseymour15 , based on recent activity ;)

**Review by adrums86 — APPROVED** [review]
LGTM. Thank you for fixing this!

**Review by wseymour15 — APPROVED** [review]
Looks good, thanks for contributing! It would be nice if there was an event listener called `one` on the transmuxer which just handled a single event and then disposed of the listener, but since that currently does not exist, I think this is a fine solution!

**Comment by arturparkhisenko** [comment]
How we can merge it to wrap it up? :) cc @dzianis-dashkevich if you can help us here.

**Comment by dzianis-dashkevich** [comment]
@arturparkhisenko merged! Thank you for this contribution

**Pull request merged**
